[versions]
flyway = "8.5.13"
h2 = "2.1.214"
kotest = "5.4.2"
kotestSpring = "1.1.2"
kotlin = "1.7.10"
micrometer = "1.9.3"
mockk = "1.12.5"
postgresql = "42.5.0"
springSecurityAuthorization = "0.3.1"
