[versions]
flyway = "8.5.13"
h2 = "2.1.214"
kotest = "5.3.1"
kotestSpring = "1.1.1"
kotlin = "1.7.0"
micrometer = "1.9.1"
mockk = "1.12.4"
postgresql = "42.4.0"
springBoot = "2.7.1"
springSecurityAuthorization = "0.3.1"
spring = "5.3.21"
