[versions]
flyway = "8.0.4"
h2 = "1.4.200"
kotest = "5.0.0"
kotestSpring = "1.1.0"
kotlin = "1.6.0"
mockk = "1.11.0"
postgresql = "42.3.1"
springBoot = "2.6.0"
springSecurity = "5.6.0"
springSecurityAuthorization = "0.2.0"
springVersion = "5.3.13"
