[versions]
flyway = "8.3.0"
h2 = "1.4.200"
kotest = "5.0.3"
kotestSpring = "1.1.0"
kotlin = "1.6.0"
mockk = "1.12.1"
postgresql = "42.3.1"
springBoot = "2.6.2"
springSecurity = "5.6.1"
springSecurityAuthorization = "0.2.1"
spring = "5.3.14"
