[versions]
flyway = "8.5.4"
h2 = "2.1.210"
kotest = "5.2.1"
kotestSpring = "1.1.0"
kotlin = "1.6.0"
micrometer = "1.8.4"
mockk = "1.12.2"
postgresql = "42.3.3"
springBoot = "2.6.5"
springSecurityAuthorization = "0.2.3"
spring = "5.3.17"
