[versions]
flyway = "8.5.11"
h2 = "2.1.212"
kotest = "5.2.1"
kotestSpring = "1.1.0"
kotlin = "1.6.21"
micrometer = "1.9.0"
mockk = "1.12.2"
postgresql = "42.3.5"
springBoot = "2.7.0"
springSecurityAuthorization = "0.2.3"
spring = "5.3.20"
