[versions]
flyway = "8.5.0"
h2 = "2.1.210"
kotest = "5.1.0"
kotestSpring = "1.1.0"
kotlin = "1.6.0"
micrometer = "1.8.3"
mockk = "1.12.2"
postgresql = "42.3.3"
springBoot = "2.6.4"
springSecurityAuthorization = "0.2.2"
spring = "5.3.16"
