[versions]
flyway = "8.4.1"
h2 = "2.0.206"
kotest = "5.0.3"
kotestSpring = "1.1.0"
kotlin = "1.6.0"
mockk = "1.12.2"
postgresql = "42.3.1"
springBoot = "2.6.3"
springSecurity = "5.6.1"
springSecurityAuthorization = "0.2.1"
spring = "5.3.15"
