server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: false

security:
  issuer-uri: "http://localhost:9000"

management:
  endpoints:
    web:
      path-mapping.info: ${ACTUATOR_INFO_PATH}
      path-mapping.metrics: ${ACTUATOR_METRICS_PATH}
      path-mapping.prometheus: ${ACTUATOR_PROMETHEUS_PATH}
      path-mapping.flyway: ${ACTUATOR_FLYWAY_PATH}
